// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateHorizontalSlider('levelSlider', { onchange: 'levelChanged', continuous: true });
    CreateText('gnugoLevelLbl', { text: 'Gnugo level' });
    CreateText('levelValueLbl', { text: '8' });
    CreateShape('rectangleShape', { rightImageWidth: 2, leftImageWidth: 2 });
    CreateText('handicapLbl', { text: 'Handicap' });
    CreateText('handicapValueLbl', { text: '0' });
    CreateText('playLbl', { text: 'Play' });
    CreateGlassButton('newbutton', { text: 'New Game', onclick: 'newClicked' });
    CreateGlassButton('passbutton', { text: 'Pass', onclick: 'passClicked' });
    CreateText('message', { text: ' ' });
    CreateText('komiLbl1', { text: 'Komi' });
    CreateHorizontalSlider('handicapSlider', { continuous: true, onchange: 'handicapChanged' });
    CreateShape('centerMessageBackground', { rightImageWidth: 29, leftImageWidth: 29 });
    CreateText('centerMessageLbl', { text: 'Loading' });
}
window.addEventListener('load', setupParts, false);
