// This file was generated by Dashcode from Apple Computer, Inc.
// You may edit this file to customize your Dashboard widget.

var hSlider, lSlider;
var preferences;

function load()
{
	$('blackOption').innerText = getLocalizedString('black');
	$('whiteOption').innerText = getLocalizedString('white');
	setupParts();
	loadPreferences();
	hSlider = new StepsSlider('handicapSlider', ['0','2','3','4','5','6','7','8','9'], 'handicapValueLbl');
	lSlider = new StepsSlider('levelSlider', ['1','2','3','4','5','6','7','8','9','10'], 'levelValueLbl');
	var configuration = new Configuration("./gnugo", 9);
	configuration.setGnuGoPlayedCallback(gnuGoPlayed);
	configuration.setGnuGoPassedCallback(cpuPassed);
	configuration.setGnuGoResignedCallback(cpuResigned);
	configuration.setMoveAcceptedCallback(drawStone);
	configuration.setInvalidMoveCallback(invalidMove);
	configuration.setFinalScoreCallback(gameEnded);
	configuration.setCapturedStonesCallback(stonesWereCaptured);
	configuration.setUndoneCallback(undoOK);
	configuration.setHandicapCallback(drawHandicap);
	initGnuGo(configuration, preferences);
}

function loadPreferences()
{
	preferences = new Preferences();
	preferences.setPlayerColor(widget.preferenceForKey("playerColor") || "Black");
	preferences.setKomi(widget.preferenceForKey("komi") || "5.5");
	preferences.setHandicap(widget.preferenceForKey("handicap") || "0");
	preferences.setLevel(widget.preferenceForKey("level") || "8");
}

function savePreferences()
{
	widget.setPreferenceForKey(preferences.getKomi(), "komi");
	widget.setPreferenceForKey(preferences.getPlayerColor(), "playerColor");
	widget.setPreferenceForKey(preferences.getHandicap(), "handicap");
	widget.setPreferenceForKey(preferences.getLevel(), "level");
}

function remove()
{
	closeGnuGo();
}

function hide()
{
	// your widget has just been hidden stop any timers to
	// prevent cpu usage
}

function show()
{
	// your widget has just been shown.  restart any timers
	// and adjust your interface as needed 
}

function showBack(event)
{
	// your widget needs to show the back

	var front = $("front");
	var back = $("back");

	if (window.widget)
		widget.prepareForTransition("ToBack");

	front.style.display="none";
	back.style.display="block";
	
	if (window.widget)
		setTimeout('widget.performTransition();', 0);
		
	$('handicapSlider').object.refresh();
	$('levelSlider').object.refresh();
	colorCombo.value = preferences.getPlayerColor();
	komiField.value = preferences.getKomi();
	hSlider.setLabel(preferences.getHandicap());
	lSlider.setLabel(preferences.getLevel());
}

function showFront(event)
{
	// your widget needs to show the front
	preferences.setPlayerColor(colorCombo.value);
	preferences.setKomi(komiField.value);
	preferences.setHandicap($('handicapValueLbl').innerText);
	preferences.setLevel($('levelValueLbl').innerText);
	savePreferences();

	var front = $("front");
	var back = $("back");

	if (window.widget)
		widget.prepareForTransition("ToFront");

	front.style.display="block";
	back.style.display="none";
	
	if (window.widget)
		setTimeout('widget.performTransition();', 0);
}

if (window.widget)
{
	widget.onremove = remove;
	widget.onhide = hide;
	widget.onshow = show;
}

var Board = function() { 
	this.size = 9;
	this.X0 = 36; // x origin in pixels, top left node (A9)
	this.Y0 = 39; // y origin in pixels, top left node (A9)
	this.stepX = 31.12; // px, between each node
	this.stepY = 31; // px, between each node
	this.tolerance = 14; // in pixels, around each node 
	this.stoneOffsetX = -16; // in pixels, about half the width of the stone image
	this.stoneOffsetY = -18; // in pixels, about half the height of the stone image 
}
Board.prototype = {
	getStoneX : function(vertice) {
				return this.X0 + this.stepX * (vertice.X -1) + this.stoneOffsetX;
			},
	getStoneY : function(vertice) {
				return this.Y0 + this.stepY * (this.size-vertice.Y) + this.stoneOffsetY;
			}
}

var board = new Board();
var lastPlayerMoves = new Array();
var lastGnuMoves = new Array();
var userCanPlay = true;
var firstCall = true;

// Event
function placeStone(event) 
{	
	if (!userCanPlay) {
		displayMessage(getLocalizedString("Please wait"));
		return;
	}
	clearMessage();
	var vertice = getVertice(event);
	if (vertice != null) {
		userCanPlay = false;
		think(true);
		lastPlayerMoves.push(vertice);
		move(vertice);
	}
}

// Callback
function drawHandicap(vertices)
{
	vertices.each(function(vertice) {
		drawStone("black", vertice);
	});
	if (preferences.gnuColor == "w") userCanPlay = false;
}

// Interface : Computes the coordinates of a mouse event to return a vertice.
function getVertice(event)
{
	var coordX = -1;
	var coordY = -1;
	for (i=1; i<=board.size; i++) {
		var pointX = board.X0+(i-1)*board.stepX;
		if (Math.abs(event.x - pointX) <= board.tolerance) {
			coordX = i;
			break;
		}
	}
	for (i=1; i<=board.size; i++) {
		var pointY = board.Y0+(i-1)*board.stepY;
		if (Math.abs(event.y - pointY) <= board.tolerance) {
			coordY = i;
			break;
		}
	}
	if (coordX == -1 || coordY == -1) {
		return null;
	}
	coordY = (board.size+1)-coordY;
	return new Vertice(coordX, coordY);
}

// Callback function
function gnuGoPlayed(color, vertice)
{
	lastGnuMoves.push(vertice);
	think(false);
	drawStone(color, vertice);
	clearMessage();
	userCanPlay = true;
}

/*
	Interface : Draws a stone of the given color at the given vertice
	color = 'b' | 'w' | 'black' | 'white'
*/
function drawStone(color, vertice)
{
	if (firstCall) {
		clearCenterMessage();
		firstCall = false;
	}
	if (vertice == "pass") return;
	
	var stone = document.createElement("div");
	stone.id = vertice.getCoords();
	stone.style.left = board.getStoneX(vertice) + 'px';
	stone.style.top = board.getStoneY(vertice) + 'px';
	if (color == "w" || color == "white") {
		stone.className = "whiteStone";
	}
	else if (color == "b" || color == "black") {
		stone.className = "blackStone";
	}
	else throw "Invalid Color";
	
	setSelectedStone(color, vertice);
	$('tock').Play();
	$('stones').appendChild(stone);
}


// Interface : Sets the "last played" indicator
function setSelectedStone(color, vertice)
{
	$('selectedStone').style.left = board.getStoneX(vertice) + 'px';
	$('selectedStone').style.top = board.getStoneY(vertice) + 'px';
	$('selectedStone').className = getFullColor(color) + "SelectedStone";
}


// Interface : hides the "last played" indicator
function hideSelectedStone()
{
	$('selectedStone').className = "noSelectedStone";
}


// Callback function
function invalidMove()
{
	think(false);
	displayMessage(getLocalizedString("Invalid move"));
	userCanPlay = true;
}


// Event
function passClicked(event) 
{
	if (!userCanPlay) {
		displayMessage(getLocalizedString("Please wait"));
		return;
	}
	think(true);
	pass();
}


// Callback function
function stonesWereCaptured(color, totalCaptured)
{
	var className = getFullColor(getOtherColor(color)) + "Stone";
	var removeCapturedStones = function(presentStonesList) {
		var stones = $A(document.getElementsByClassName(className, 'stones'));
		stones.each(function(verticeDiv) {
			if (presentStonesList.indexOf(verticeDiv.id) == -1) {
				$('stones').removeChild(verticeDiv);
			}
		});
	}
	getStonesPositions(getOtherColor(color), removeCapturedStones);
}


// Interface : Shows an indicator that CPU is thinking
function think(thinking)
{
	if (thinking)
		$('thinking').style.display = 'block';
	else
		$('thinking').style.display = 'none';
}


// Undo is not activated in this version
function undoClicked(event) 
{
	if (!userCanPlay) {
		displayMessage(getLocalizedString("Please wait"));
		return;
	}
	undoLastMove();
}

// Callback function
function undoOK()
{
	if (lastPlayerMoves.length > 0) {
		$('stones').removeChild($(lastPlayerMoves.pop().getCoords()));
	}
	if (lastGnuMoves.length > 0) {
		$('stones').removeChild($(lastGnuMoves.pop().getCoords()));
	}
	setSelectedStone(config.gnuColor, lastGnuMoves[lastGnuMoves.length-1]);
}

// Callback function
function cpuPassed()
{
	userCanPlay = true;
	think(false);
	hideSelectedStone();
	displayMessage(getLocalizedString("Passed"));
}

// Callback function
function cpuResigned()
{
	displayMessage(getLocalizedString("Resigned"));
}

// Callback function
function gameEnded(score)
{
	think(false);
	hideSelectedStone();
	displayCenterMessage(getFormattedScore(score));
}

// Util : returns a localized string informing the final score
function getFormattedScore(score)
{
	var color = score.substring(0,1);
	var gap = score.substring(2, score.length);
	
	return capitalizeFirst(getLocalizedString(getFullColor(color))) + ' ' + getLocalizedString('winsBy') + ' ' + gap + ' ' + getLocalizedString('points');
}

// Event
function newClicked(event) 
{
	think(false);
	clearMessage();
	clearCenterMessage();
	hideSelectedStone();
	$('stones').innerHTML = "";
	startNewGame(preferences);
}

// Interface : clears the status message
function clearMessage()
{
	displayMessage('');
}

// Interface : displays a status message
function displayMessage(msg)
{
	$('message').innerHTML = msg;
}

// Interface: displays an important message in the center of the widget
function displayCenterMessage(msg)
{
	if (centerMessage.style.display == '') {
		//init display
		centerMessage.style.display = 'none';
		centerMessageLbl.style.display = 'none';
		centerMessageBackground.style.display = 'none';
	}
	$('centerMessageLbl').innerHTML = msg;
	if (msg == '') {
		Element.hide('centerMessage');
		return;
	}
	centerMessageLbl.style.display = 'block';
	centerMessageBackground.style.display = 'block';
	//centerMessage.style.display = 'block';
	Effect.Appear(centerMessage);
}

// Event: Hides the center message when it is clicked
function centerMessageClicked() 
{
	clearCenterMessage();
}

function clearCenterMessage()
{
	if ($('centerMessage').display != 'none')
	{
		Effect.Fade('centerMessage');
	}
}

//Util
function capitalizeFirst(str)
{
	return str.substring(0,1).toUpperCase() + str.substring(1, str.length);
}

// Util : returns the opposite color (b or w)
function getOtherColor(color)
{
	var c = color.toLowerCase();
	return (c == "w" || c == "white") ? "b" : "w";
}

// Util : returns the full name of the color
function getFullColor(color)
{
	var c = color.toLowerCase();
	return (c == "w" || c == "white") ? "white" : "black";
}

// Opens my site
function contact(event) 
{
	widget.openURL('http://lesiteajulien.free.fr');
}

// Event
function handicapChanged(value) 
{
	if (hSlider) hSlider.onchange(value);
}

// Event
function levelChanged(value)
{
	if (lSlider) lSlider.onchange(value);
}

// Object that manages the sliders with fixed positions.
var StepsSlider = function(sliderId, labels, labelDivId)
{
	this.tolerance = 0.02;
	this.labels = labels;
	this.n = labels.length;
	this.interval = 1 / (this.n-1);
	this.sliderId = sliderId;
	this.labelDivId = labelDivId;
}
StepsSlider.prototype = {
	init : function()
	{
		this.slider = $(this.sliderId).object;
		this.labelDiv = $(this.labelDivId);
	},
	onchange : function(value) 
	{
		if (!this.slider) this.init();
		
		for (var i=0; i<this.n; i++) {
			if (Math.abs(value - (i*this.interval)) < this.tolerance) {
				this.labelDiv.innerText = this.labels[i];
				return;
			}
		}
		
		var attractionDistance = (this.interval / 2);
		for (var i=0; i<this.n; i++) {
			if (value < (i*this.interval + attractionDistance)) {
				this.slider.setValue(i*this.interval);
				this.slider.refresh();
				return;
			}
		}
		this.slider.setValue(1);
		this.slider.refresh();
	},
	setLabel : function(label)
	{
		if (!this.slider) this.init();
		for (var i=0; i<this.n; i++) {
			if (label == this.labels[i]) {
				this.slider.setValue(i*this.interval);
				this.slider.refresh();
				return;
			}
		}
		this.slider.setValue(1);
		this.slider.refresh();
	}
}
